PROMPTS = {
    "autogen": {
        "assistant_system": "You are a problem-solving agent.",
        "assistant_user": """
Below is the relevant content retrieved from memory and the current task. Please provide your response.

# Retrieved Content
{memory_content}

# Current Task
{task_description}
""".strip(),
        "user_proxy_system": "You are a problem-solving agent.",
        "user_proxy_user": """
Below is the relevant content retrieved from memory, the strategy provided by the assistant, and the current task requirements. Please provide your response.

# Retrieved Content
{memory_content}

# Implementation Strategy
{assistant_output}

# Current Task
{task_description}
""".strip(),
    },
    "camel": {
        "user_proxy_system": "You are a problem-solving agent.",
        "user_proxy_user": """
Below is the relevant content retrieved from memory and the current task. Please provide your response in accordance with the task requirements.

# Retrieved Content
{memory_content}

# Current Task
{task_description}
""".strip(),
        "actor_system": """
You will be given a question and a user proxy agent's answer for that question. Please consider the user proxy agent's answer and provide your own answer.
""".strip(),
        "actor_user": """
Below is the relevant content retrieved from memory, the answer provided by the user proxy agent, and the current task. Please provide your response in accordance with the task requirements.

# Retrieved Content
{memory_content}

# User Proxy Answer
{userproxy_output}

# Current Task
{task_description}
""".strip(),
        "critic_system": """
You are a strategy evaluator. Your task is to review the response provided by the actor agent for the current problem.

- If you believe the actor agent's response is correct and has no issues, reply only with: "Agree".
- If you believe the actor agent's response has issues, provide brief and concise feedback only (keep your response short and within 3 sentences).
""".strip(),
        "critic_user": """
Below are the relevant contents retrieved from memory, the response given by the actor agent, and the requirements of the current task. Please provide your review.

# Retrieved Content
{memory_content}

# Actor Output
{actor_output}

# Current Task
{task_description}
""".strip(),
        "summarizer_system": """
You will be given a question, the responses produced by actor agents, and the corresponding feedback from critic agents for that question. Please provide your response in accordance with the task requirements.
""".strip(),
        "summarizer_user": """
# Retrieved Content
{memory_content}

# Actor Output
{actor_output}

# Critic Feedback
{critic_output}

# Current Task
{task_description}
""".strip(),
    },
    "macnet": {
        "actor_system": "You are a problem-solving agent.",
        "actor_user": """
Below is the relevant content retrieved from memory and the current task. Please provide your response in accordance with the task requirements.

# Retrieved Content
{memory_content}

# Current Task
{task_description}
""".strip(),
        "critic_system": """
You are a strategy evaluator. Your task is to review the response provided by the actor agent for the current problem.

- If you believe the actor agent's response is correct and has no issues, reply only with: "Agree".
- If you believe the actor agent's response has issues, provide brief and concise feedback only (keep your response short and within 3 sentences).
""".strip(),
        "critic_user": """
Below are the relevant contents retrieved from memory, the response given by the actor agent, and the requirements of the current task. Please provide your review.

# Retrieved Content
{memory_content}

# Actor Output
{actor_output}

# Current Task
{task_description}
""".strip(),
        "summarizer_system": """
You are a summarizer agent.
You will be given a question, the responses produced by actor agents, and the corresponding feedback from critic agents for that question.
""".strip(),
        "summarizer_user": """
Below are the relevant materials retrieved from memory, the responses generated by the actor agents, and the corresponding feedback from the critic agents.
Please provide your response in accordance with the task requirements.

# Retrieved Content
{memory_content}

# Actor1 Response and Critic1 Feedback
{feedback_page1}

# Actor2 Response and Critic2 Feedback
{feedback_page2}

# Current Task
{task_description}
""".strip(),
        "feedback_page": """
## Actor Response
{actor_output}

## Critic Feedback
{critic_output}
""".strip(),
    },
}

