from __future__ import annotations

from importlib import import_module

__version__ = "0.1.0"

__all__ = [
    "AgentMessage",
    "SSABatch",
    "SSAManifestDataset",
    "SSASample",
    "SSATraceRecord",
    "SSADistiller",
    "ConsolidationResult",
    "ClusterMemory",
    "DiskClusterStore",
    "DiskLatentStore",
    "DiskPageTableStore",
    "ExplicitTeacher",
    "HashMIPSRetriever",
    "HashEmbeddingEncoder",
    "IPCBus",
    "KernelConfig",
    "MASConfig",
    "MASExecutionTrace",
    "MASPromptTemplate",
    "MASRoleSpec",
    "MASTopologySpec",
    "MASTurn",
    "LatentStudent",
    "LatentPrefixProjector",
    "LatentTensor",
    "MemoryCluster",
    "MemoryAgent",
    "OSKernel",
    "PageTable",
    "PageTableEntry",
    "PipelineConfig",
    "PipelineRunResult",
    "PointerAddress",
    "PointerDrivenSSAMemPipeline",
    "PointerPreferenceSample",
    "QueryLatentComposer",
    "PersistentMemoryBackend",
    "PointerSearchHit",
    "ResolvedIPCMessage",
    "RunConfig",
    "BaseRetriever",
    "RuntimeConfig",
    "SoftPromptBatch",
    "UserSpaceGenerationOutput",
    "UserSpaceMAS",
    "build_ssa_data_from_traces",
    "build_ssa_manifest_without_latents",
    "ssa_records_from_hf_dataset",
    "collect_synthetic_pointer_preferences",
    "compute_keyword_recall",
    "evaluate_ssa_latent_distances",
    "evaluate_pointer_routing",
    "extract_probe_keywords",
    "generate_synthetic_api_ssa_records",
    "initialize_pointer_vocabulary",
    "load_alignment_checkpoint",
    "load_ssa_manifest",
    "load_pointer_preferences",
    "probe_ssa_generation",
    "pointer_tokens",
    "pointer_preferences_from_rollouts",
    "save_ssa_manifest",
    "save_ssa_trace_records",
    "save_pointer_preferences",
    "split_ssa_manifest",
]

_LAZY_IMPORTS = {
    "RuntimeConfig": ("ssamem.config", "RuntimeConfig"),
    "KernelConfig": ("ssamem.config", "KernelConfig"),
    "MASConfig": ("ssamem.config", "MASConfig"),
    "RunConfig": ("ssamem.config", "RunConfig"),
    "PipelineConfig": ("ssamem.config", "PipelineConfig"),
    "AgentMessage": ("ssamem.data_models", "AgentMessage"),
    "ClusterMemory": ("ssamem.data_models", "ClusterMemory"),
    "ConsolidationResult": ("ssamem.data_models", "ConsolidationResult"),
    "DiskClusterStore": ("ssamem.storage", "DiskClusterStore"),
    "DiskLatentStore": ("ssamem.storage", "DiskLatentStore"),
    "DiskPageTableStore": ("ssamem.storage", "DiskPageTableStore"),
    "LatentTensor": ("ssamem.data_models", "LatentTensor"),
    "MASExecutionTrace": ("ssamem.data_models", "MASExecutionTrace"),
    "MASTurn": ("ssamem.data_models", "MASTurn"),
    "MemoryCluster": ("ssamem.data_models", "MemoryCluster"),
    "PageTable": ("ssamem.data_models", "PageTable"),
    "PageTableEntry": ("ssamem.data_models", "PageTableEntry"),
    "PipelineRunResult": ("ssamem.data_models", "PipelineRunResult"),
    "PointerAddress": ("ssamem.data_models", "PointerAddress"),
    "PointerSearchHit": ("ssamem.data_models", "PointerSearchHit"),
    "ResolvedIPCMessage": ("ssamem.data_models", "ResolvedIPCMessage"),
    "BaseRetriever": ("ssamem.retrieval", "BaseRetriever"),
    "HashEmbeddingEncoder": ("ssamem.retrieval", "HashEmbeddingEncoder"),
    "HashMIPSRetriever": ("ssamem.retrieval", "HashMIPSRetriever"),
    "IPCBus": ("ssamem.kernelspace", "IPCBus"),
    "MemoryAgent": ("ssamem.kernelspace", "MemoryAgent"),
    "MASPromptTemplate": ("ssamem.mas", "MASPromptTemplate"),
    "MASRoleSpec": ("ssamem.mas", "MASRoleSpec"),
    "MASTopologySpec": ("ssamem.mas", "MASTopologySpec"),
    "OSKernel": ("ssamem.kernelspace", "OSKernel"),
    "PointerDrivenSSAMemPipeline": ("ssamem.pipeline", "PointerDrivenSSAMemPipeline"),
    "PersistentMemoryBackend": ("ssamem.storage", "PersistentMemoryBackend"),
    "SSABatch": ("ssamem.trainingspace", "SSABatch"),
    "SSAManifestDataset": ("ssamem.trainingspace", "SSAManifestDataset"),
    "SSASample": ("ssamem.trainingspace", "SSASample"),
    "SSATraceRecord": ("ssamem.ssa_data", "SSATraceRecord"),
    "SSADistiller": ("ssamem.trainingspace", "SSADistiller"),
    "ExplicitTeacher": ("ssamem.trainingspace", "ExplicitTeacher"),
    "LatentStudent": ("ssamem.trainingspace", "LatentStudent"),
    "LatentPrefixProjector": ("ssamem.trainingspace", "LatentPrefixProjector"),
    "QueryLatentComposer": ("ssamem.trainingspace", "QueryLatentComposer"),
    "PointerPreferenceSample": ("ssamem.ssa_data", "PointerPreferenceSample"),
    "build_ssa_data_from_traces": ("ssamem.trainingspace", "build_ssa_data_from_traces"),
    "build_ssa_manifest_without_latents": ("ssamem.ssa_data", "build_ssa_manifest_without_latents"),
    "ssa_records_from_hf_dataset": ("ssamem.ssa_data", "ssa_records_from_hf_dataset"),
    "collect_synthetic_pointer_preferences": ("ssamem.ssa_data", "collect_synthetic_pointer_preferences"),
    "compute_keyword_recall": ("ssamem.trainingspace", "compute_keyword_recall"),
    "evaluate_ssa_latent_distances": ("ssamem.trainingspace", "evaluate_ssa_latent_distances"),
    "evaluate_pointer_routing": ("ssamem.trainingspace", "evaluate_pointer_routing"),
    "extract_probe_keywords": ("ssamem.trainingspace", "extract_probe_keywords"),
    "generate_synthetic_api_ssa_records": ("ssamem.ssa_data", "generate_synthetic_api_ssa_records"),
    "initialize_pointer_vocabulary": ("ssamem.trainingspace", "initialize_pointer_vocabulary"),
    "load_alignment_checkpoint": ("ssamem.trainingspace", "load_alignment_checkpoint"),
    "load_ssa_manifest": ("ssamem.trainingspace", "load_ssa_manifest"),
    "load_pointer_preferences": ("ssamem.trainingspace", "load_pointer_preferences"),
    "probe_ssa_generation": ("ssamem.trainingspace", "probe_ssa_generation"),
    "pointer_tokens": ("ssamem.trainingspace", "pointer_tokens"),
    "pointer_preferences_from_rollouts": ("ssamem.ssa_data", "pointer_preferences_from_rollouts"),
    "save_ssa_manifest": ("ssamem.trainingspace", "save_ssa_manifest"),
    "save_ssa_trace_records": ("ssamem.ssa_data", "save_ssa_trace_records"),
    "save_pointer_preferences": ("ssamem.ssa_data", "save_pointer_preferences"),
    "split_ssa_manifest": ("ssamem.trainingspace", "split_ssa_manifest"),
    "SoftPromptBatch": ("ssamem.userspace", "SoftPromptBatch"),
    "UserSpaceMAS": ("ssamem.userspace", "UserSpaceMAS"),
    "UserSpaceGenerationOutput": ("ssamem.userspace", "UserSpaceGenerationOutput"),
}


def __getattr__(name: str):
    if name not in _LAZY_IMPORTS:
        raise AttributeError(f"module 'ssamem' has no attribute '{name}'")
    module_name, attr_name = _LAZY_IMPORTS[name]
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
